/**
 * Social Stars — All Game Data
 * Scenarios, Emotion Match, How Would You Feel, Social Stories,
 * Badges, Themes, and Grounding Steps
 */

/* ===== CATEGORIES ===== */
const CATEGORIES = [
    { id: "emotions", title: "Understanding Emotions", emoji: "\u{1F60A}", description: "Learn to recognise how people feel" },
    { id: "conversations", title: "Conversations", emoji: "\u{1F4AC}", description: "Practice talking with others" },
    { id: "friendships", title: "Being a Good Friend", emoji: "\u{1F91D}", description: "Learn about friendship skills" },
    { id: "body-language", title: "Body Language", emoji: "\u{1F64B}", description: "Understand what bodies tell us" },
    { id: "tricky-situations", title: "Tricky Situations", emoji: "\u{1F914}", description: "Figure out what to do when things are hard" },
    { id: "feelings-check", title: "My Own Feelings", emoji: "\u{1F496}", description: "Understand and manage your feelings" }
];

/* ===== SCENARIOS (with difficulty 1-3) ===== */
const SCENARIOS = {
    emotions: [
        { difficulty:1, emoji:"\u{1F622}", text:"Your friend Sam is sitting alone at lunch. Their eyes are red and they're looking down at the table. How do you think Sam is feeling?", choices:[{text:"Sam is feeling sad",correct:true},{text:"Sam is feeling excited",correct:false},{text:"Sam is feeling angry",correct:false}], correctFeedback:"That's right! Red eyes and looking down are signs someone is sad. You're great at reading feelings!", encourageFeedback:"Good try! When someone has red eyes and looks down, they're usually feeling sad. Those are important clues to notice." },
        { difficulty:1, emoji:"\u{1F604}", text:"Maya just found out she's going to the amusement park this weekend. She's jumping up and down and has a big smile. How is Maya feeling?", choices:[{text:"Maya is feeling scared",correct:false},{text:"Maya is feeling excited and happy",correct:true},{text:"Maya is feeling bored",correct:false}], correctFeedback:"Exactly! Jumping up and down with a big smile means Maya is super excited and happy!", encourageFeedback:"Nice thinking! When someone jumps up and down with a big smile, they're usually feeling excited and happy." },
        { difficulty:1, emoji:"\u{1F620}", text:"Tom's little brother just broke his favourite toy. Tom's face is red, his fists are clenched, and he's breathing fast. How is Tom feeling?", choices:[{text:"Tom is feeling happy",correct:false},{text:"Tom is feeling tired",correct:false},{text:"Tom is feeling angry",correct:true}], correctFeedback:"You got it! A red face, clenched fists, and fast breathing are signs of anger. Great job!", encourageFeedback:"Good guess! When someone's face is red and fists are clenched, they're usually feeling angry." },
        { difficulty:2, emoji:"\u{1F630}", text:"It's Lily's first day at a new school. She's biting her nails, her voice is very quiet, and she keeps looking around. How might Lily be feeling?", choices:[{text:"Lily is feeling nervous or worried",correct:true},{text:"Lily is feeling proud",correct:false},{text:"Lily is feeling silly",correct:false}], correctFeedback:"That's right! Nail biting and a quiet voice are signs of feeling nervous. It's normal to feel that way in new places!", encourageFeedback:"Nice try! When someone bites their nails and speaks quietly, they're usually feeling nervous or worried." },
        { difficulty:2, emoji:"\u{1F62E}", text:"Dad walks into his surprise birthday party. His eyes go wide, his mouth opens, and he puts his hands on his face. How is Dad feeling?", choices:[{text:"Dad is feeling bored",correct:false},{text:"Dad is feeling surprised",correct:true},{text:"Dad is feeling confused",correct:false}], correctFeedback:"Yes! Wide eyes and an open mouth are classic signs of surprise. You're a feelings detective!", encourageFeedback:"Good thinking! When someone's eyes go wide and their mouth opens suddenly, they're usually feeling surprised." },
        { difficulty:3, emoji:"\u{1F614}", text:"Your friend got a good grade but doesn't look happy. They're smiling a little but their shoulders are slumped. What might they be feeling?", choices:[{text:"They're feeling proud and excited",correct:false},{text:"They might be disappointed — maybe they expected an even better grade",correct:true},{text:"They're feeling angry at the teacher",correct:false}], correctFeedback:"Great observation! Sometimes people can look okay on the outside but feel disappointed inside. Noticing small clues like slumped shoulders is really perceptive!", encourageFeedback:"Good try! When someone smiles but their body looks droopy, they might be hiding disappointment. It's tricky to spot, but you're learning!" },
        { difficulty:3, emoji:"\u{1F633}", text:"A classmate is laughing really loudly but their eyes look watery. What might be going on?", choices:[{text:"They're just really happy",correct:false},{text:"They might be laughing to hide that they're upset",correct:true},{text:"They're being silly",correct:false}], correctFeedback:"Wow, great insight! Sometimes people laugh to cover up sadness or embarrassment. Noticing the watery eyes was really clever!", encourageFeedback:"That's a tricky one! Sometimes people laugh even when they're upset — it's a way of hiding feelings. Watery eyes are a clue that something else might be going on." }
    ],
    conversations: [
        { difficulty:1, emoji:"\u{1F44B}", text:"You see a new kid in your class. They're standing alone. What's a good way to start a conversation?", choices:[{text:"\"Hi! I'm [your name]. What's your name?\"",correct:true},{text:"Walk past them without saying anything",correct:false},{text:"Stare at them from far away",correct:false}], correctFeedback:"Perfect! Saying hi and sharing your name is a friendly way to start talking to someone new!", encourageFeedback:"The best way to start is simple \u2014 just say \"Hi, I'm [your name]!\" and ask theirs." },
        { difficulty:1, emoji:"\u{1F5E3}\uFE0F", text:"Your friend is telling you about their weekend. What should you do while they're talking?", choices:[{text:"Look at them and listen",correct:true},{text:"Start talking about your weekend instead",correct:false},{text:"Walk away to do something else",correct:false}], correctFeedback:"Great answer! Looking at someone and listening shows you care. That's called being a good listener!", encourageFeedback:"When someone is talking to us, the kindest thing is to look at them and listen. We can share our story after they finish." },
        { difficulty:2, emoji:"\u{1F937}", text:"Someone asks you a question but you don't know the answer. What's a good thing to say?", choices:[{text:"Make up an answer",correct:false},{text:"\"I'm not sure, but we could find out together!\"",correct:true},{text:"Just stay quiet",correct:false}], correctFeedback:"Wonderful! It's totally okay not to know something. Offering to find out together is really kind!", encourageFeedback:"It's always okay to say \"I'm not sure.\" Nobody knows everything! Suggesting to find the answer together is a great way to connect." },
        { difficulty:2, emoji:"\u{1F60A}", text:"Your classmate shows you a drawing they made. You can tell they worked really hard. What could you say?", choices:[{text:"\"That's not very good\"",correct:false},{text:"Say nothing",correct:false},{text:"\"I can see you worked really hard on this! I like the colours.\"",correct:true}], correctFeedback:"That's a lovely thing to say! Noticing someone's effort makes people feel really good.", encourageFeedback:"When someone shows us their work, it's kind to notice their effort. You could say \"I can see you worked hard on this!\"" },
        { difficulty:3, emoji:"\u{1F504}", text:"You've been talking about your favourite game for a while. Your friend looks like they want to say something. What should you do?", choices:[{text:"Keep talking because your story is interesting",correct:false},{text:"Pause and ask \"What do you think?\" or \"What about you?\"",correct:true},{text:"Talk even faster so you can finish",correct:false}], correctFeedback:"Excellent! Pausing to let others speak is a super important conversation skill!", encourageFeedback:"In conversations, it's important to take turns. If you notice someone wants to speak, try pausing and asking \"What do you think?\"" },
        { difficulty:3, emoji:"\u{1F910}", text:"You notice your friend has been quiet all day and isn't joining in conversations. What could you do?", choices:[{text:"Ignore it \u2014 they're probably fine",correct:false},{text:"Tell everyone that your friend is being weird",correct:false},{text:"Quietly ask them \"Hey, are you okay? You seem quiet today.\"",correct:true}], correctFeedback:"That's really thoughtful! Checking in privately shows you care without putting them on the spot.", encourageFeedback:"When someone is unusually quiet, a kind thing to do is check in privately. A simple \"Are you okay?\" can mean a lot." }
    ],
    friendships: [
        { difficulty:1, emoji:"\u{1F3AE}", text:"Your friend wants to play a different game than you. What's the best thing to do?", choices:[{text:"Say \"We always have to play what I want!\"",correct:false},{text:"Take turns \u2014 play their game first, then yours",correct:true},{text:"Stop playing and walk away",correct:false}], correctFeedback:"Great idea! Taking turns is one of the best friendship skills!", encourageFeedback:"Friends take turns choosing activities. You could play their game first, then yours. That way everyone has fun!" },
        { difficulty:1, emoji:"\u{1F614}", text:"Your friend is having a bad day and seems really upset. What could you do?", choices:[{text:"Tell them to stop being sad",correct:false},{text:"Ignore them",correct:false},{text:"Sit with them and say \"I'm here if you want to talk\"",correct:true}], correctFeedback:"That's really caring! Sometimes people just need to know someone is there for them.", encourageFeedback:"When a friend is upset, one of the best things you can do is just be there. You could say \"I'm here if you want to talk.\"" },
        { difficulty:2, emoji:"\u{1F64A}", text:"Your friend tells you a secret. Another kid asks you what the secret is. What should you do?", choices:[{text:"Tell them the secret",correct:false},{text:"Say \"Sorry, I can't share that. It's not my secret to tell.\"",correct:true},{text:"Make up a different secret",correct:false}], correctFeedback:"That's exactly right! Keeping secrets safe is a big part of being a trustworthy friend.", encourageFeedback:"When someone trusts us with a secret, it's important to keep it safe. You could say \"Sorry, that's not my secret to tell.\"" },
        { difficulty:2, emoji:"\u{1F382}", text:"Your friend got a really cool birthday present, but you didn't get one. How could you handle this?", choices:[{text:"Feel happy for your friend and say \"That's so cool!\"",correct:true},{text:"Say \"That's not fair! I want one too!\"",correct:false},{text:"Pretend you don't care",correct:false}], correctFeedback:"Wonderful! Being happy for a friend even when you feel a little jealous is really mature!", encourageFeedback:"It's normal to feel a little jealous! But a great friendship skill is being happy for your friend." },
        { difficulty:3, emoji:"\u{1F62C}", text:"You accidentally said something that hurt your friend's feelings. What should you do?", choices:[{text:"Pretend it didn't happen",correct:false},{text:"Say \"I'm sorry I said that. I didn't mean to hurt your feelings.\"",correct:true},{text:"Blame them for being too sensitive",correct:false}], correctFeedback:"That's the right thing to do! Saying sorry and meaning it is one of the most important things in any friendship.", encourageFeedback:"When we accidentally hurt someone, the best thing is to say \"I'm sorry\" and mean it." },
        { difficulty:3, emoji:"\u{1F465}", text:"Two of your friends are fighting and both want you to pick a side. What could you do?", choices:[{text:"Pick the friend you like more",correct:false},{text:"Say \"I care about both of you. I don't want to pick sides, but I hope you can work it out.\"",correct:true},{text:"Stop being friends with both of them",correct:false}], correctFeedback:"That's a really mature response! You can care about both friends without taking sides. That takes real wisdom!", encourageFeedback:"It's hard when friends fight! But you don't have to pick sides. You can say \"I care about both of you\" and encourage them to talk it out." }
    ],
    "body-language": [
        { difficulty:1, emoji:"\u{1F644}", text:"Someone keeps looking at the clock and tapping their foot while you're talking. What might their body be telling you?", choices:[{text:"They're really interested",correct:false},{text:"They might be in a hurry or need to go",correct:true},{text:"They're very relaxed",correct:false}], correctFeedback:"Good eye! Looking at the clock and tapping feet usually means someone is in a hurry.", encourageFeedback:"When someone keeps looking at the clock and tapping their foot, their body is saying \"I need to go.\"" },
        { difficulty:1, emoji:"\u{1F917}", text:"Your grandma sees you after a long time. She opens her arms wide and smiles big. What is her body language saying?", choices:[{text:"She wants to give you a hug \u2014 she's happy to see you!",correct:true},{text:"She's telling you to stop",correct:false},{text:"She's feeling scared",correct:false}], correctFeedback:"That's right! Open arms and a big smile mean someone is happy and wants a hug!", encourageFeedback:"When someone opens their arms wide and smiles, they're saying \"I'm so happy to see you!\"" },
        { difficulty:2, emoji:"\u{1F636}", text:"A kid at school has their arms crossed tightly and is looking away from the group. What might they be feeling?", choices:[{text:"Happy and included",correct:false},{text:"They might be feeling left out or uncomfortable",correct:true},{text:"Sleepy",correct:false}], correctFeedback:"Great observation! Crossed arms and looking away can mean someone feels left out.", encourageFeedback:"When someone crosses their arms and looks away, they might be feeling left out or uncomfortable." },
        { difficulty:2, emoji:"\u{1F440}", text:"A student is leaning forward, making eye contact, and nodding while the teacher talks. What does this mean?", choices:[{text:"The student is bored",correct:false},{text:"The student is confused",correct:false},{text:"The student is listening carefully and interested",correct:true}], correctFeedback:"Exactly! Leaning forward, eye contact, and nodding are all signs of active listening!", encourageFeedback:"Leaning forward, looking at someone, and nodding are ways our body says \"I'm listening!\"" },
        { difficulty:3, emoji:"\u{1FAE3}", text:"Someone is talking to you but keeps looking at the ground and speaking very quietly. What might this mean?", choices:[{text:"They're feeling confident",correct:false},{text:"They might be feeling shy or nervous",correct:true},{text:"They're feeling angry",correct:false}], correctFeedback:"That's right! Looking down and speaking quietly often means someone is feeling shy or nervous.", encourageFeedback:"When someone looks at the ground and speaks quietly, they're usually feeling shy or nervous." },
        { difficulty:3, emoji:"\u{1F9D0}", text:"Your friend says \"I'm fine\" but they're not making eye contact, their voice is flat, and they're fidgeting. Should you believe them?", choices:[{text:"Yes, they said they're fine so they must be",correct:false},{text:"Their body language suggests they might not be fine \u2014 you could gently check in again",correct:true},{text:"They're probably just tired",correct:false}], correctFeedback:"Great insight! Sometimes words and body language don't match. Gently checking in shows you really care!", encourageFeedback:"Sometimes people say \"I'm fine\" when they're not. If their body language doesn't match their words, it's kind to gently ask again." }
    ],
    "tricky-situations": [
        { difficulty:1, emoji:"\u{1F624}", text:"Someone at school says something mean to you. What's a good way to handle it?", choices:[{text:"Say something mean back",correct:false},{text:"Take a deep breath and walk away, then tell a trusted adult",correct:true},{text:"Pretend you didn't hear it",correct:false}], correctFeedback:"That's a really strong choice! Walking away takes courage, and telling an adult is smart.", encourageFeedback:"The best thing to do is take a deep breath, walk away, and tell a trusted adult." },
        { difficulty:1, emoji:"\u{1F6AB}", text:"Your friends want you to do something you know is wrong. What should you do?", choices:[{text:"Do it so they'll still like you",correct:false},{text:"Say \"No, I don't want to do that\" \u2014 even if it's hard",correct:true},{text:"Go along with it quietly",correct:false}], correctFeedback:"That's really brave! Saying no when something is wrong takes a lot of courage.", encourageFeedback:"It's important to say \"I don't want to do that\" when something feels wrong. True friends will respect your choice." },
        { difficulty:2, emoji:"\u{1F615}", text:"You see two friends arguing. What could you do?", choices:[{text:"Pick a side",correct:false},{text:"Ignore it completely",correct:false},{text:"Calmly suggest they talk it out, or get an adult to help",correct:true}], correctFeedback:"That's a wise choice! Helping friends talk calmly shows great problem-solving skills!", encourageFeedback:"When friends argue, you could suggest they talk it out, or ask an adult for help." },
        { difficulty:2, emoji:"\u{1F633}", text:"You made a mistake in front of the whole class and some kids laughed. How could you handle this?", choices:[{text:"Everyone makes mistakes! Take a breath and say \"Oops!\" with a smile",correct:true},{text:"Run out of the classroom",correct:false},{text:"Get angry at the kids who laughed",correct:false}], correctFeedback:"That's a great attitude! Being able to laugh at yourself is a real superpower!", encourageFeedback:"Everyone makes mistakes. Taking a breath and saying \"Oops!\" shows confidence and bravery." },
        { difficulty:3, emoji:"\u{1F504}", text:"You really want a turn on the swing but someone else is using it. What should you do?", choices:[{text:"Push them off",correct:false},{text:"Ask nicely: \"Can I have a turn when you're done?\"",correct:true},{text:"Stand really close and stare until they leave",correct:false}], correctFeedback:"Perfect! Asking nicely is always the best approach!", encourageFeedback:"The best way is to ask nicely: \"Can I have a turn when you're done?\"" },
        { difficulty:3, emoji:"\u{1F4F1}", text:"Someone posts something unkind about you online. What should you do?", choices:[{text:"Post something mean about them back",correct:false},{text:"Don't respond \u2014 save a screenshot and tell a trusted adult",correct:true},{text:"Delete all your accounts",correct:false}], correctFeedback:"Smart thinking! Not responding and telling an adult is the safest and wisest choice. You handled that like a pro!", encourageFeedback:"When someone is unkind online, the best thing is to not respond, save evidence, and tell a trusted adult. They can help you handle it." }
    ],
    "feelings-check": [
        { difficulty:1, emoji:"\u{1F621}", text:"You're feeling really angry because something unfair happened. What's a good way to calm down?", choices:[{text:"Yell and throw things",correct:false},{text:"Take 5 deep breaths, count to 10, or squeeze a stress ball",correct:true},{text:"Keep all the anger inside",correct:false}], correctFeedback:"Great strategy! Deep breaths and counting help your brain calm down!", encourageFeedback:"There are helpful ways to calm down, like taking 5 deep breaths or counting to 10." },
        { difficulty:1, emoji:"\u{1F61F}", text:"You're feeling worried about a test tomorrow. What could help?", choices:[{text:"Stay up all night worrying",correct:false},{text:"Tell someone how you feel and make a plan to study a little bit",correct:true},{text:"Decide not to go to school",correct:false}], correctFeedback:"Smart thinking! Talking about worries makes them smaller!", encourageFeedback:"A great thing to do is tell someone how you feel, then make a small plan like studying for 15 minutes." },
        { difficulty:2, emoji:"\u{1F61E}", text:"You're feeling sad and you don't really know why. What's a good thing to do?", choices:[{text:"It's okay to feel sad sometimes. Talk to someone you trust.",correct:true},{text:"Pretend to be happy",correct:false},{text:"Stay in your room alone",correct:false}], correctFeedback:"That's really wise! Sometimes we feel sad without a clear reason, and that's completely okay.", encourageFeedback:"It's okay to feel sad, even when you don't know why! Talking to someone you trust can really help." },
        { difficulty:2, emoji:"\u{1F929}", text:"You're SO excited but you're in class. What could you do?", choices:[{text:"Shout out your exciting news",correct:false},{text:"Squeeze your hands under the desk and wait for break time",correct:true},{text:"Run around the classroom",correct:false}], correctFeedback:"Great self-control! Waiting for the right moment shows real maturity!", encourageFeedback:"In class, try squeezing your hands under the desk to use that energy. Share your news at break time!" },
        { difficulty:3, emoji:"\u{1F624}", text:"Your sibling keeps bothering you and you're getting really frustrated. What could help?", choices:[{text:"Hit or push them",correct:false},{text:"Calmly say \"I need some space right now, please\" and walk to another room",correct:true},{text:"Scream as loud as you can",correct:false}], correctFeedback:"That's a really mature way to handle it! Using your words to ask for space is a powerful skill.", encourageFeedback:"A great strategy is to use calm words: \"I need some space right now.\" Then go to another room." },
        { difficulty:3, emoji:"\u{1F616}", text:"You feel like crying but you're at school and feel embarrassed. What could you do?", choices:[{text:"Hold it all in and pretend everything is fine",correct:false},{text:"Ask to go to the bathroom or a quiet space, and let yourself feel the feelings",correct:true},{text:"Get angry at everyone around you",correct:false}], correctFeedback:"That's a really healthy choice! It's okay to need a quiet moment. Finding a safe space to feel your feelings is a sign of strength, not weakness.", encourageFeedback:"It's okay to cry! If you need a moment, you can ask to go somewhere quiet. Taking care of your feelings is important and brave." }
    ]
};


/* ===== EMOTION MATCH DATA ===== */
const EMOTION_MATCH = [
    { face: "\u{1F604}", answer: "Happy", options: ["Happy", "Sad", "Angry", "Scared"] },
    { face: "\u{1F622}", answer: "Sad", options: ["Excited", "Sad", "Surprised", "Bored"] },
    { face: "\u{1F621}", answer: "Angry", options: ["Happy", "Shy", "Angry", "Tired"] },
    { face: "\u{1F628}", answer: "Scared", options: ["Proud", "Scared", "Silly", "Calm"] },
    { face: "\u{1F632}", answer: "Surprised", options: ["Surprised", "Angry", "Sad", "Nervous"] },
    { face: "\u{1F60A}", answer: "Proud", options: ["Worried", "Bored", "Proud", "Confused"] },
    { face: "\u{1F634}", answer: "Tired", options: ["Excited", "Tired", "Happy", "Angry"] },
    { face: "\u{1F61E}", answer: "Disappointed", options: ["Disappointed", "Scared", "Silly", "Proud"] },
    { face: "\u{1F60D}", answer: "Loving", options: ["Angry", "Loving", "Bored", "Nervous"] },
    { face: "\u{1F914}", answer: "Confused", options: ["Happy", "Sad", "Confused", "Excited"] },
    { face: "\u{1F633}", answer: "Embarrassed", options: ["Embarrassed", "Proud", "Angry", "Calm"] },
    { face: "\u{1F60E}", answer: "Confident", options: ["Shy", "Confident", "Worried", "Sad"] }
];

/* ===== HOW WOULD YOU FEEL DATA ===== */
const HOW_WOULD_YOU_FEEL = [
    { emoji: "\u{1F3C6}", text: "You just won first place in a race at school!", feelings: ["Proud", "Excited", "Happy", "Nervous"], responses: { "Proud": "It makes sense to feel proud! You worked hard and it paid off.", "Excited": "Excitement is a great feeling! Winning is really thrilling.", "Happy": "Of course you'd feel happy! That's a wonderful achievement.", "Nervous": "Some people do feel nervous even when they win \u2014 that's totally okay! Big moments can bring lots of feelings." } },
    { emoji: "\u{1F3E0}", text: "Your family is moving to a new house in a different town.", feelings: ["Worried", "Sad", "Excited", "Scared"], responses: { "Worried": "It's very normal to feel worried about a big change. New things can be uncertain.", "Sad": "Feeling sad about leaving makes total sense \u2014 you might miss your friends and familiar places.", "Excited": "Some people feel excited about new adventures! A new house can be fun to explore.", "Scared": "It's okay to feel scared about big changes. Most people feel that way sometimes." } },
    { emoji: "\u{1F381}", text: "It's your birthday and all your friends are coming to your party!", feelings: ["Excited", "Happy", "Nervous", "Grateful"], responses: { "Excited": "Birthdays are exciting! It's fun to celebrate with friends.", "Happy": "Of course! Being surrounded by friends on your birthday is a great feeling.", "Nervous": "Some people feel nervous at parties, even their own! That's completely normal.", "Grateful": "Feeling grateful is really lovely \u2014 it shows you appreciate your friends." } },
    { emoji: "\u{1F4DD}", text: "Your teacher asks you to read out loud in front of the whole class.", feelings: ["Nervous", "Scared", "Proud", "Okay"], responses: { "Nervous": "Lots of people feel nervous about reading aloud. That's one of the most common worries!", "Scared": "It can feel scary to be the centre of attention. That's a very normal feeling.", "Proud": "Some people feel proud when they get to share! That's great confidence.", "Okay": "Feeling okay about it is great! Not everything has to be a big deal." } },
    { emoji: "\u{1F436}", text: "You find a lost puppy in your neighbourhood.", feelings: ["Worried", "Happy", "Excited", "Sad"], responses: { "Worried": "It makes sense to worry about the puppy \u2014 you want it to be safe!", "Happy": "Puppies can make us feel happy! They're so cute.", "Excited": "Finding a puppy is exciting! You might want to help it find its home.", "Sad": "You might feel sad that the puppy is lost and alone. That shows empathy!" } },
    { emoji: "\u{1F3A4}", text: "You're about to perform in the school talent show.", feelings: ["Nervous", "Excited", "Scared", "Proud"], responses: { "Nervous": "Almost everyone feels nervous before performing! Even professional singers do.", "Excited": "The thrill of performing can be really exciting! That energy can help you do great.", "Scared": "Stage fright is very real and very normal. Taking deep breaths can help!", "Proud": "Feeling proud of yourself for being brave enough to perform is wonderful!" } },
    { emoji: "\u{1F4A9}", text: "Someone made fun of your lunch at school.", feelings: ["Sad", "Angry", "Embarrassed", "Hurt"], responses: { "Sad": "It's sad when people are unkind about something personal. Your feelings are valid.", "Angry": "It's natural to feel angry when someone is mean. That's your brain saying 'that's not fair!'", "Embarrassed": "Feeling embarrassed is understandable. But remember \u2014 there's nothing wrong with your lunch!", "Hurt": "Feeling hurt makes sense. Mean comments can sting, even about small things." } },
    { emoji: "\u{1F3D5}\uFE0F", text: "You're going on a camping trip and will sleep in a tent for the first time.", feelings: ["Excited", "Nervous", "Happy", "Scared"], responses: { "Excited": "Camping is an adventure! Sleeping in a tent can be really fun.", "Nervous": "New experiences can make us nervous. That's your brain getting ready for something new!", "Happy": "Being in nature and trying new things can bring a lot of happiness!", "Scared": "It's okay to feel scared about sleeping somewhere new. Lots of people feel that way the first time." } }
];

/* ===== SOCIAL STORIES ===== */
const SOCIAL_STORIES = [
    {
        id: "birthday-party", title: "Going to a Birthday Party", emoji: "\u{1F382}",
        description: "What to expect and how to have fun",
        steps: [
            { emoji: "\u{1F381}", text: "I've been invited to a birthday party! I might feel excited or a little nervous. Both feelings are okay." },
            { emoji: "\u{1F457}", text: "Before the party, I can get ready. I'll wear comfortable clothes and maybe bring a gift for the birthday person." },
            { emoji: "\u{1F6AA}", text: "When I arrive, I can say \"Hi!\" and \"Happy Birthday!\" to the birthday person. If I feel shy, I can wave and smile." },
            { emoji: "\u{1F3AE}", text: "At the party, there might be games, food, and music. I can join in the activities or watch for a bit until I feel comfortable." },
            { emoji: "\u{1F370}", text: "When it's time for cake, everyone sings Happy Birthday. I can sing along or just listen \u2014 both are fine!" },
            { emoji: "\u{1F44B}", text: "When the party is over, I can say \"Thank you for inviting me!\" and \"Goodbye!\" I did a great job!" }
        ]
    },
    {
        id: "joining-game", title: "Joining a Game at Recess", emoji: "\u{26BD}",
        description: "How to ask to play with others",
        steps: [
            { emoji: "\u{1F440}", text: "I see some kids playing a game at recess. I'd like to join them!" },
            { emoji: "\u{1F6B6}", text: "I walk over to the group. I stand nearby where they can see me." },
            { emoji: "\u{1F4AC}", text: "I wait for a good moment (like a pause in the game) and ask: \"Can I play too?\" or \"Is there room for one more?\"" },
            { emoji: "\u{1F60A}", text: "If they say yes \u2014 great! I join in and follow the rules of the game." },
            { emoji: "\u{1F914}", text: "If they say no, that's okay. I can say \"Maybe next time!\" and find something else to do. It doesn't mean they don't like me." },
            { emoji: "\u{2B50}", text: "I'm proud of myself for being brave enough to ask! That takes courage." }
        ]
    },
    {
        id: "new-school", title: "Starting at a New School", emoji: "\u{1F3EB}",
        description: "What your first day might be like",
        steps: [
            { emoji: "\u{1F31F}", text: "Today is my first day at a new school. I might feel nervous, excited, or both. That's completely normal!" },
            { emoji: "\u{1F6AA}", text: "When I arrive, a teacher or helper will show me where to go. I can ask questions if I'm not sure about something." },
            { emoji: "\u{1F4DA}", text: "In class, I'll find my seat. I can look around and see who's sitting near me." },
            { emoji: "\u{1F44B}", text: "I can introduce myself to the person next to me: \"Hi, I'm [name]. I'm new here.\" Most kids are friendly!" },
            { emoji: "\u{1F372}", text: "At lunch, I can sit with someone who seems friendly, or ask a teacher where to sit. It's okay to eat quietly too." },
            { emoji: "\u{1F3E0}", text: "At the end of the day, I did it! Each day will get a little easier. I'm brave for trying something new." }
        ]
    },
    {
        id: "doctor-visit", title: "Going to the Doctor", emoji: "\u{1F3E5}",
        description: "What happens at a check-up",
        steps: [
            { emoji: "\u{1F697}", text: "Today I'm going to the doctor for a check-up. This is to make sure my body is healthy." },
            { emoji: "\u{1F6CB}\uFE0F", text: "In the waiting room, I might wait for a little while. I can read a book, play a quiet game, or just sit." },
            { emoji: "\u{1F469}\u200D\u2695\uFE0F", text: "The doctor or nurse will call my name. They'll take me to a room and might check my height and weight." },
            { emoji: "\u{1FA7A}", text: "The doctor might listen to my heart, look in my ears, and check my throat. These things don't hurt!" },
            { emoji: "\u{1F4AC}", text: "If I feel scared or uncomfortable, I can tell the doctor or my parent. It's okay to say \"I'm nervous.\"" },
            { emoji: "\u{1F31F}", text: "When it's done, I did a great job! Going to the doctor helps keep me healthy and strong." }
        ]
    },
    {
        id: "saying-sorry", title: "Saying Sorry", emoji: "\u{1F495}",
        description: "How to apologise when you make a mistake",
        steps: [
            { emoji: "\u{1F614}", text: "Sometimes I might do or say something that hurts someone's feelings. Everyone makes mistakes \u2014 that's okay." },
            { emoji: "\u{1F4AD}", text: "First, I think about what happened. What did I do? How did it make the other person feel?" },
            { emoji: "\u{1F6B6}", text: "I go to the person I hurt. I look at them (or near them) so they know I'm being serious." },
            { emoji: "\u{1F4AC}", text: "I say: \"I'm sorry for [what I did]. I didn't mean to hurt your feelings.\" I try to mean it." },
            { emoji: "\u{1F91D}", text: "I ask: \"Are you okay?\" or \"Is there anything I can do to make it better?\"" },
            { emoji: "\u{1F4AA}", text: "I try not to do the same thing again. Saying sorry and learning from mistakes makes me a good friend." }
        ]
    }
];

/* ===== GROUNDING STEPS (5-4-3-2-1) ===== */
const GROUNDING_STEPS = [
    { emoji: "\u{1F440}", text: "Look around and name 5 things you can SEE.\n\nFor example: a window, a book, your shoes, a clock, a tree outside.\n\nTake your time \u2014 really look at each one." },
    { emoji: "\u{270B}", text: "Notice 4 things you can TOUCH.\n\nFor example: your shirt, the chair, your hair, the desk.\n\nReally feel the texture of each one." },
    { emoji: "\u{1F442}", text: "Listen for 3 things you can HEAR.\n\nFor example: birds outside, the clock ticking, someone talking.\n\nClose your eyes if it helps you listen." },
    { emoji: "\u{1F443}", text: "Notice 2 things you can SMELL.\n\nFor example: your lunch, fresh air, soap on your hands.\n\nTake a slow, deep sniff." },
    { emoji: "\u{1F445}", text: "Notice 1 thing you can TASTE.\n\nFor example: toothpaste, water, your last snack.\n\nYou're doing amazing! You should feel calmer now. \u{1F31F}" }
];

/* ===== THERMOMETER DATA ===== */
const THERM_LEVELS = [
    { emoji: "\u{1F60A}", label: "Calm", color: "#4caf50", tip: "You're feeling calm and peaceful. That's a great place to be! Enjoy this feeling." },
    { emoji: "\u{1F610}", label: "A little upset", color: "#8bc34a", tip: "You're a little bit bothered. That's okay! Try taking a few slow breaths or talking to someone about it." },
    { emoji: "\u{1F615}", label: "Medium upset", color: "#ffeb3b", tip: "Your feelings are getting stronger. This is a good time to use a calming tool \u2014 like deep breathing or the 5-4-3-2-1 game." },
    { emoji: "\u{1F61F}", label: "Very upset", color: "#ff9800", tip: "You're feeling a lot right now. That's okay! Try going to a quiet place, squeezing something soft, or talking to a trusted adult." },
    { emoji: "\u{1F62D}", label: "Overwhelmed", color: "#f44336", tip: "Your feelings are really big right now. You need help! Please talk to a parent, teacher, or trusted adult. You could also try the Calm Down Corner." }
];

/* ===== BADGES ===== */
const BADGES = [
    { id: "first-star", emoji: "\u{2B50}", name: "First Star", desc: "Earn your first star", condition: (s) => s.totalStars >= 1 },
    { id: "star-10", emoji: "\u{1F31F}", name: "Rising Star", desc: "Earn 10 stars", condition: (s) => s.totalStars >= 10 },
    { id: "star-25", emoji: "\u{1F4AB}", name: "Shining Bright", desc: "Earn 25 stars", condition: (s) => s.totalStars >= 25 },
    { id: "star-50", emoji: "\u{1F320}", name: "Shooting Star", desc: "Earn 50 stars", condition: (s) => s.totalStars >= 50 },
    { id: "star-100", emoji: "\u{1F3C6}", name: "Superstar", desc: "Earn 100 stars", condition: (s) => s.totalStars >= 100 },
    { id: "emotions-done", emoji: "\u{1F60A}", name: "Feelings Expert", desc: "Complete Understanding Emotions", condition: (s) => (s.categoriesCompleted || []).includes("emotions") },
    { id: "conversations-done", emoji: "\u{1F4AC}", name: "Great Talker", desc: "Complete Conversations", condition: (s) => (s.categoriesCompleted || []).includes("conversations") },
    { id: "friends-done", emoji: "\u{1F91D}", name: "Best Friend", desc: "Complete Being a Good Friend", condition: (s) => (s.categoriesCompleted || []).includes("friendships") },
    { id: "body-done", emoji: "\u{1F64B}", name: "Body Reader", desc: "Complete Body Language", condition: (s) => (s.categoriesCompleted || []).includes("body-language") },
    { id: "tricky-done", emoji: "\u{1F914}", name: "Problem Solver", desc: "Complete Tricky Situations", condition: (s) => (s.categoriesCompleted || []).includes("tricky-situations") },
    { id: "feelings-done", emoji: "\u{1F496}", name: "Self-Aware Star", desc: "Complete My Own Feelings", condition: (s) => (s.categoriesCompleted || []).includes("feelings-check") },
    { id: "all-cats", emoji: "\u{1F451}", name: "Social Champion", desc: "Complete all 6 categories", condition: (s) => (s.categoriesCompleted || []).length >= 6 },
    { id: "emotion-match", emoji: "\u{1F3AD}", name: "Face Reader", desc: "Complete Emotion Match", condition: (s) => s.emotionMatchDone },
    { id: "checkin-3", emoji: "\u{1F4D3}", name: "Journal Keeper", desc: "Do 3 daily check-ins", condition: (s) => (s.checkins || []).length >= 3 },
    { id: "checkin-7", emoji: "\u{1F4D6}", name: "Feelings Tracker", desc: "Do 7 daily check-ins", condition: (s) => (s.checkins || []).length >= 7 },
    { id: "calm-used", emoji: "\u{1F9D8}", name: "Calm Master", desc: "Use the Calm Down Corner", condition: (s) => s.calmUsed },
    { id: "story-read", emoji: "\u{1F4D6}", name: "Story Explorer", desc: "Read a Social Story", condition: (s) => s.storyRead },
    { id: "perfect-round", emoji: "\u{1F48E}", name: "Perfect Round", desc: "Get all answers right in one topic", condition: (s) => s.perfectRound },
    { id: "tone-done", emoji: "\u{1F5E3}\uFE0F", name: "Tone Detective", desc: "Complete Tone of Voice", condition: (s) => s.toneDone },
    { id: "persp-done", emoji: "\u{1F440}", name: "Empathy Star", desc: "Complete Their Point of View", condition: (s) => s.perspDone },
    { id: "vocab-done", emoji: "\u{1F4D6}", name: "Word Wizard", desc: "Read all Feelings Words", condition: (s) => s.vocabDone },
    { id: "coping-done", emoji: "\u{1F3B4}", name: "Coping Pro", desc: "View 5 Coping Cards", condition: (s) => s.copingDone },
    { id: "rules-read", emoji: "\u{1F4CB}", name: "Rule Knower", desc: "Read the Social Rules", condition: (s) => s.rulesRead },
    { id: "timer-used", emoji: "\u{23F1}\uFE0F", name: "Time Keeper", desc: "Use the Visual Timer", condition: (s) => s.timerUsed },
    { id: "star-150", emoji: "\u{1F31F}", name: "Mega Star", desc: "Earn 150 stars", condition: (s) => s.totalStars >= 150 },
    { id: "star-200", emoji: "\u{1F4A5}", name: "Legendary", desc: "Earn 200 stars", condition: (s) => s.totalStars >= 200 },
    { id: "all-badges", emoji: "\u{1F3C5}", name: "Badge Collector", desc: "Earn 20 badges", condition: (s) => (s.earnedBadges || []).length >= 20 }
];

/* ===== THEMES ===== */
const THEMES = [
    { id: "default", name: "Starlight", emoji: "\u{2B50}", desc: "The classic look", starsNeeded: 0, className: "", starIcon: "\u{2B50}", celebIcon: "\u{1F31F}", welcomeChar: "\u{1F31F}" },
    { id: "unicorn", name: "Unicorn Dreams", emoji: "\u{1F984}", desc: "Sparkles and magic", starsNeeded: 5, className: "theme-unicorn", starIcon: "\u{1F984}", celebIcon: "\u{2728}", welcomeChar: "\u{1F984}" },
    { id: "princess", name: "Princess Kingdom", emoji: "\u{1F451}", desc: "Royal and golden", starsNeeded: 15, className: "theme-princess", starIcon: "\u{1F451}", celebIcon: "\u{1F490}", welcomeChar: "\u{1F478}" },
    { id: "fairy", name: "Fairy Tales", emoji: "\u{1F9DA}", desc: "Magical and enchanting", starsNeeded: 25, className: "theme-fairy", starIcon: "\u{1F33C}", celebIcon: "\u{1F9DA}", welcomeChar: "\u{1F9DA}" },
    { id: "ocean", name: "Ocean Adventure", emoji: "\u{1F30A}", desc: "Under the sea", starsNeeded: 35, className: "theme-ocean", starIcon: "\u{1F41A}", celebIcon: "\u{1F42C}", welcomeChar: "\u{1F42C}" },
    { id: "cherry", name: "Cherry Blossom", emoji: "\u{1F338}", desc: "Soft and peaceful", starsNeeded: 45, className: "theme-cherry", starIcon: "\u{1F338}", celebIcon: "\u{1F33A}", welcomeChar: "\u{1F338}" },
    { id: "katseye", name: "Katseye", emoji: "\u{1F431}", desc: "Cool and confident", starsNeeded: 55, className: "theme-katseye", starIcon: "\u{1F431}", celebIcon: "\u{1F3A4}", welcomeChar: "\u{1F3B6}" },
    { id: "space", name: "Space Explorer", emoji: "\u{1F680}", desc: "To the stars and beyond", starsNeeded: 70, className: "theme-space", starIcon: "\u{1FA90}", celebIcon: "\u{1F680}", welcomeChar: "\u{1F680}" },
    { id: "galaxy", name: "Galaxy Purple", emoji: "\u{1F52E}", desc: "Mysterious and deep", starsNeeded: 85, className: "theme-galaxy", starIcon: "\u{1F52E}", celebIcon: "\u{1F30C}", welcomeChar: "\u{1F52E}" },
    { id: "rainbow", name: "Rainbow Magic", emoji: "\u{1F308}", desc: "All the colours!", starsNeeded: 100, className: "theme-rainbow", starIcon: "\u{1F308}", celebIcon: "\u{1F389}", welcomeChar: "\u{1F308}" }
];

/* ===== CHECK-IN RESPONSES ===== */
const CHECKIN_RESPONSES = {
    great: "That's wonderful! I'm so glad you're feeling great today! \u{1F31F} Keep spreading that positive energy!",
    good: "Nice! Feeling good is a great way to be. \u{1F60A} I hope your day stays lovely!",
    okay: "Feeling okay is perfectly fine! \u{1F44D} Not every day has to be amazing. You're doing great just by checking in.",
    sad: "I'm sorry you're feeling sad today. \u{1F49C} Remember, it's okay to feel this way. Would you like to visit the Calm Down Corner?",
    angry: "It sounds like something is bothering you. \u{1F4AA} Feeling angry is normal. Taking some deep breaths might help. The Calm Down Corner is here for you!",
    worried: "Worries can feel really big sometimes. \u{1F917} Talking about them can help make them smaller. You're brave for sharing how you feel!"
};


/* ===== TONE OF VOICE DATA ===== */
var TONE_OF_VOICE = [
    { emoji:"\u{1F60F}", quote:"\"Oh great, another test. Just what I wanted.\"", context:"A student says this after the teacher announces a surprise test. They roll their eyes.", answer:"Sarcastic", options:["Serious","Sarcastic","Joking","Excited"], correctFeedback:"That's right! They don't actually want a test. The eye roll and tone tell us they mean the opposite of what they said. That's sarcasm!", encourageFeedback:"Tricky one! When someone says something positive but their face and voice show the opposite, they're being sarcastic \u2014 meaning the opposite of their words." },
    { emoji:"\u{1F602}", quote:"\"You're SO slow, you'd lose a race to a snail!\"", context:"Your best friend says this while laughing after you take a long time choosing an ice cream flavour.", answer:"Joking", options:["Mean","Joking","Serious","Sarcastic"], correctFeedback:"Exactly! Your friend is teasing in a playful way. The laughing and the silly exaggeration (racing a snail!) tell us it's a joke.", encourageFeedback:"When a friend says something silly while laughing, they're usually joking! The key clues are: they're smiling, it's exaggerated, and they're your friend." },
    { emoji:"\u{1F6D1}", quote:"\"Please don't touch that. It's very fragile.\"", context:"A museum guide says this calmly while pointing to a glass sculpture.", answer:"Serious", options:["Joking","Sarcastic","Serious","Angry"], correctFeedback:"Right! The museum guide is being serious \u2014 they genuinely don't want you to touch it. Their calm, clear tone tells us this is a real instruction.", encourageFeedback:"When someone speaks calmly and clearly about something important, they're being serious. There's no laughing or eye-rolling \u2014 they mean exactly what they say." },
    { emoji:"\u{1F611}", quote:"\"Sure, I LOVE waiting in line for an hour.\"", context:"Your mum says this while standing in a very long queue at the shop, sighing.", answer:"Sarcastic", options:["Serious","Happy","Sarcastic","Joking"], correctFeedback:"You got it! Mum doesn't actually love waiting. The sigh and the emphasis on \"LOVE\" are clues that she means the opposite.", encourageFeedback:"When someone emphasises a word strongly and their body language doesn't match (like sighing), they're usually being sarcastic \u2014 saying the opposite of what they mean." },
    { emoji:"\u{1F923}", quote:"\"I'm basically a professional chef now!\"", context:"Your friend says this proudly after successfully making toast for the first time.", answer:"Joking", options:["Serious","Sarcastic","Bragging","Joking"], correctFeedback:"That's right! They know making toast doesn't make them a chef \u2014 they're being funny about a small achievement. The exaggeration is the clue!", encourageFeedback:"When someone exaggerates something small in a fun way, they're joking! They know toast isn't gourmet cooking \u2014 they're being playfully silly." },
    { emoji:"\u{1F468}\u200D\u2695\uFE0F", quote:"\"You need to take this medicine twice a day with food.\"", context:"A doctor says this while writing a prescription, looking at you directly.", answer:"Serious", options:["Joking","Sarcastic","Serious","Nervous"], correctFeedback:"Correct! The doctor is giving important health instructions. Their direct eye contact and clear words tell us this is serious.", encourageFeedback:"Doctors give serious instructions about health. When someone looks at you directly and speaks clearly about something important, they're being serious." },
    { emoji:"\u{1F612}", quote:"\"Oh wonderful, my phone just died. Perfect timing.\"", context:"Your sister says this when her phone runs out of battery right before she needed to call someone.", answer:"Sarcastic", options:["Happy","Sarcastic","Joking","Confused"], correctFeedback:"Spot on! She's frustrated, not happy. Saying \"wonderful\" and \"perfect\" when something bad happens is classic sarcasm.", encourageFeedback:"When someone uses positive words (wonderful, perfect) about a negative situation, and they sound annoyed, that's sarcasm! They mean the opposite." },
    { emoji:"\u{1F609}", quote:"\"Watch out, I might eat ALL the pizza before you get any!\"", context:"Your dad says this with a wink while putting pizza on the table for everyone.", answer:"Joking", options:["Serious","Threatening","Joking","Sarcastic"], correctFeedback:"Right! Dad's wink and the fact that he's serving everyone tells us he's joking. He's not really going to eat it all!", encourageFeedback:"A wink is a big clue that someone is joking! Dad is being playful \u2014 he's putting pizza out for everyone, so he clearly doesn't mean it." }
];

/* ===== PERSPECTIVE TAKING DATA ===== */
var PERSPECTIVE_TAKING = [
    { emoji:"\u{1F466}", text:"You're playing with a toy and your little brother asks if he can have a turn. You say \"No, I'm still playing.\" He walks away with his head down. How does your brother probably feel?", choices:[{text:"Sad and disappointed",correct:true},{text:"Happy for you",correct:false},{text:"Angry at the toy",correct:false}], correctFeedback:"That's right. When someone walks away with their head down after being told no, they're probably feeling sad and disappointed. Even though you were still playing, it helps to notice how others feel.", encourageFeedback:"When someone asks for something and gets told no, then walks away with their head down, they're usually feeling sad or disappointed. Noticing this helps us be kind." },
    { emoji:"\u{1F467}", text:"You got picked for the school play but your friend didn't. Your friend says \"Congratulations\" but their smile looks forced. How might your friend be feeling?", choices:[{text:"Truly happy for you",correct:false},{text:"Happy for you but also disappointed for themselves",correct:true},{text:"Angry at the teacher",correct:false}], correctFeedback:"Great insight! People can feel two things at once. Your friend is trying to be happy for you, but they're also disappointed they didn't get picked. That's called mixed feelings.", encourageFeedback:"Sometimes people feel two things at the same time! Your friend might be happy for you AND sad for themselves. A forced smile is a clue that they're hiding some sadness." },
    { emoji:"\u{1F469}", text:"You're telling your mum about your day but she keeps looking at her phone. You feel annoyed. But then you notice she looks worried. What might be going on for her?", choices:[{text:"She doesn't care about your day",correct:false},{text:"She's being rude on purpose",correct:false},{text:"She might have received some worrying news and is distracted",correct:true}], correctFeedback:"That's really thoughtful! Sometimes when people seem distracted, they have something on their mind. Noticing her worried face shows great empathy.", encourageFeedback:"When someone seems distracted, it's not always about us. If your mum looks worried, she might have received some concerning news. Asking \"Are you okay, Mum?\" would be really kind." },
    { emoji:"\u{1F9D1}", text:"A new student joins your class mid-year. At lunch, they sit alone and don't talk to anyone. How might they be feeling?", choices:[{text:"They probably want to be alone",correct:false},{text:"Nervous, lonely, and unsure how to join in",correct:true},{text:"They don't like anyone in the class",correct:false}], correctFeedback:"That's right! Starting at a new school is really hard. They probably want to make friends but don't know how to start. Inviting them to sit with you would mean the world!", encourageFeedback:"New students often feel nervous and lonely, not unfriendly. They might not know how to start a conversation. A simple \"Want to sit with us?\" can change their whole day." },
    { emoji:"\u{1F474}", text:"Your grandpa keeps asking you the same question he asked 5 minutes ago. You feel frustrated. But why might grandpa be repeating himself?", choices:[{text:"He's trying to annoy you",correct:false},{text:"He might be forgetful because of his age, and he doesn't realise he already asked",correct:true},{text:"He wasn't listening to your answer",correct:false}], correctFeedback:"That's very understanding! As people get older, their memory can change. Grandpa isn't trying to annoy you \u2014 he genuinely might not remember asking. Being patient with him is really kind.", encourageFeedback:"Older people sometimes have trouble with memory. Grandpa probably doesn't realise he already asked. Being patient and answering kindly shows real maturity and love." },
    { emoji:"\u{1F46B}", text:"Your friend cancels plans with you to hang out with someone else. You feel hurt. But your friend says the other person was really upset and needed support. How might you see this differently?", choices:[{text:"Your friend is a bad friend",correct:false},{text:"Your friend was trying to help someone who really needed it \u2014 it wasn't about not wanting to see you",correct:true},{text:"The other person is more important than you",correct:false}], correctFeedback:"That's a really mature way to see it! Your friend was being kind to someone in need. It doesn't mean they don't care about you \u2014 you can always reschedule.", encourageFeedback:"Sometimes friends need to help others in tough moments. It doesn't mean you're less important! Understanding this shows real emotional intelligence." }
];

/* ===== COPING STRATEGY CARDS ===== */
var COPING_CARDS = [
    { emoji:"\u{1F4A8}", title:"Deep Belly Breaths", text:"Put your hand on your tummy. Breathe in slowly through your nose for 4 counts. Feel your tummy push out. Breathe out through your mouth for 6 counts. Do this 5 times." },
    { emoji:"\u{1F9CA}", title:"Ice Cube Hold", text:"Hold an ice cube in your hand. Focus on how it feels \u2014 cold, wet, melting. This helps your brain focus on something physical instead of big feelings." },
    { emoji:"\u{1F3B5}", title:"Hum Your Favourite Song", text:"Pick a song you love and hum it quietly. The vibration in your chest and the familiar melody can help calm your nervous system." },
    { emoji:"\u{1F4AA}", title:"Tense and Release", text:"Squeeze your fists really tight for 5 seconds. Then let go completely. Feel the difference! Do the same with your shoulders, your toes, and your face." },
    { emoji:"\u{1F30A}", title:"Wave Breathing", text:"Imagine you're at the beach. As a wave comes in, breathe in. As it goes out, breathe out. Picture the waves getting smaller and calmer." },
    { emoji:"\u{1F4AC}", title:"Talk to Someone", text:"Find a person you trust \u2014 a parent, teacher, or friend. Say \"I'm feeling [emotion] because [reason].\" You don't have to handle big feelings alone." },
    { emoji:"\u{1F3A8}", title:"Draw Your Feelings", text:"Grab some paper and draw how you feel. It doesn't have to look like anything! Use colours and shapes. Angry might be red zigzags. Sad might be blue rain." },
    { emoji:"\u{1F6B6}", title:"Take a Walk", text:"Moving your body helps your brain calm down. Walk around the room, the garden, or the school. Pay attention to what you see, hear, and feel as you walk." },
    { emoji:"\u{1F9F8}", title:"Comfort Object", text:"Hold something soft and comforting \u2014 a stuffed animal, a blanket, or a smooth stone. Squeeze it gently and focus on how it feels in your hands." },
    { emoji:"\u{1F4D6}", title:"Read or Listen to a Story", text:"Stories can take your mind to a different place. Pick a favourite book or ask someone to read to you. Let yourself get lost in the story." },
    { emoji:"\u{2708}\uFE0F", title:"Happy Place Imagination", text:"Close your eyes. Imagine your favourite place \u2014 maybe a beach, your bedroom, or grandma's house. What do you see? Hear? Smell? Stay there for a minute." },
    { emoji:"\u{1F4DD}", title:"Write It Down", text:"Grab a piece of paper and write down what's bothering you. You don't have to show anyone. Sometimes getting thoughts out of your head and onto paper helps them feel smaller." }
];


/* ===== ADDITIONAL SCENARIOS (doubles content per category) ===== */
SCENARIOS.emotions.push(
    { difficulty:1, emoji:"\u{1F60D}", text:"Your friend just got a puppy! They're hugging it and can't stop smiling. How are they feeling?", choices:[{text:"Overjoyed and loving",correct:true},{text:"Nervous",correct:false},{text:"Bored",correct:false}], correctFeedback:"Yes! Hugging and non-stop smiling are signs of pure joy and love!", encourageFeedback:"When someone hugs something and can't stop smiling, they're feeling overjoyed!" },
    { difficulty:2, emoji:"\u{1F625}", text:"Your classmate just dropped their lunch tray in the cafeteria. Everyone looked. Their face is bright red and they're looking at the floor. How might they feel?", choices:[{text:"Proud",correct:false},{text:"Embarrassed",correct:true},{text:"Excited",correct:false}], correctFeedback:"Right! A red face and looking down after something awkward means embarrassment. It happens to everyone!", encourageFeedback:"When something awkward happens in front of people, the red face and looking down are signs of embarrassment." },
    { difficulty:2, emoji:"\u{1F929}", text:"A girl just found out she made the school football team. She's pumping her fist and jumping. How is she feeling?", choices:[{text:"Proud and thrilled",correct:true},{text:"Confused",correct:false},{text:"Worried",correct:false}], correctFeedback:"Exactly! Fist pumping and jumping show she's proud and thrilled about her achievement!", encourageFeedback:"Fist pumping and jumping are big celebration moves \u2014 she's feeling proud and thrilled!" },
    { difficulty:3, emoji:"\u{1F9D0}", text:"Your friend says they're fine but they keep sighing and staring out the window. What might they actually be feeling?", choices:[{text:"Happy and content",correct:false},{text:"They might be sad or thoughtful, even though they said they're fine",correct:true},{text:"Excited about something outside",correct:false}], correctFeedback:"Great insight! Sighing and staring can mean someone is sad or deep in thought, even when they say they're fine.", encourageFeedback:"Sometimes people say they're fine when they're not. Sighing and staring are clues that something might be on their mind." },
    { difficulty:3, emoji:"\u{1F972}", text:"Your mum is watching a movie and she's smiling but also has tears in her eyes. What's going on?", choices:[{text:"She's feeling touched or moved \u2014 sometimes happy things make us cry too",correct:true},{text:"She's angry at the movie",correct:false},{text:"She's scared",correct:false}], correctFeedback:"Wonderful observation! Happy tears are real! When something is beautiful or touching, people can smile and cry at the same time.", encourageFeedback:"This is a tricky one! Sometimes people cry from happiness or being deeply moved. Smiling + tears usually means something touched their heart." }
);

SCENARIOS.conversations.push(
    { difficulty:1, emoji:"\u{1F44D}", text:"Someone gives you a compliment and says \"I like your shirt!\" What's a good response?", choices:[{text:"Ignore them",correct:false},{text:"Say \"Thank you!\" and smile",correct:true},{text:"Say \"I know, it's expensive\"",correct:false}], correctFeedback:"Perfect! A simple \"Thank you!\" with a smile is the best way to receive a compliment.", encourageFeedback:"When someone says something nice, \"Thank you!\" is always a great response. It shows you appreciate their kindness." },
    { difficulty:2, emoji:"\u{1F4F1}", text:"You're texting a friend and they send a short reply like \"k\". You're not sure if they're upset. What could you do?", choices:[{text:"Assume they hate you",correct:false},{text:"Send 20 more messages asking if they're okay",correct:false},{text:"Remember that short texts don't always mean someone is upset \u2014 they might just be busy",correct:true}], correctFeedback:"Smart thinking! Short texts often just mean someone is busy. If you're worried, you could ask \"Everything okay?\" once.", encourageFeedback:"Short texts can feel confusing! But they usually just mean someone is busy. A simple \"Everything okay?\" is fine if you're worried." },
    { difficulty:3, emoji:"\u{1F910}", text:"You accidentally interrupt someone who was talking. What should you do?", choices:[{text:"Keep talking since you already started",correct:false},{text:"Say \"Sorry, go ahead\" and let them finish",correct:true},{text:"Pretend it didn't happen",correct:false}], correctFeedback:"That's really polite! Saying \"Sorry, go ahead\" shows respect and good conversation skills.", encourageFeedback:"Interrupting happens to everyone! The best thing is to say \"Sorry, go ahead\" and let them finish their thought." }
);

SCENARIOS.friendships.push(
    { difficulty:1, emoji:"\u{1F3C3}", text:"Your friend falls down during a race. What should you do?", choices:[{text:"Keep running to win",correct:false},{text:"Stop and ask if they're okay",correct:true},{text:"Laugh at them",correct:false}], correctFeedback:"That's what a true friend does! Checking on someone who's hurt is more important than winning.", encourageFeedback:"A good friend stops to help. Asking \"Are you okay?\" shows you care more about them than winning." },
    { difficulty:2, emoji:"\u{1F3A8}", text:"Your friend is really good at drawing but you're not. You feel jealous. What's a healthy way to handle this?", choices:[{text:"Tell them their drawings aren't that good",correct:false},{text:"Appreciate their talent and ask them to teach you some tips",correct:true},{text:"Stop being friends with them",correct:false}], correctFeedback:"That's a great attitude! Everyone has different strengths. Asking a friend to teach you is a wonderful way to learn and bond.", encourageFeedback:"Jealousy is normal! But a great response is to appreciate your friend's talent and ask them to share some tips with you." },
    { difficulty:3, emoji:"\u{1F46F}", text:"You notice your friend is being left out by other kids at school. What could you do?", choices:[{text:"Join the other kids so you don't get left out too",correct:false},{text:"Invite your friend to join you and include them",correct:true},{text:"Pretend you didn't notice",correct:false}], correctFeedback:"That's really brave and kind! Including someone who's being left out can change their whole day. You'd be an amazing friend.", encourageFeedback:"It takes courage, but inviting someone who's being left out to join you is one of the kindest things you can do." }
);

SCENARIOS["body-language"].push(
    { difficulty:1, emoji:"\u{1F44F}", text:"Everyone in the audience is clapping and smiling after a school performance. What does this body language mean?", choices:[{text:"They enjoyed the show and want to show appreciation",correct:true},{text:"They're trying to scare the performers",correct:false},{text:"They're bored",correct:false}], correctFeedback:"That's right! Clapping is how we show we enjoyed something. It's a way of saying \"Great job!\"", encourageFeedback:"Clapping and smiling after a performance means the audience enjoyed it! It's their way of saying \"Well done!\"" },
    { difficulty:2, emoji:"\u{1F64E}", text:"Someone is talking to you with their hands on their hips and a stern face. What might they be feeling?", choices:[{text:"Relaxed and happy",correct:false},{text:"Frustrated or serious about something",correct:true},{text:"Sleepy",correct:false}], correctFeedback:"Good reading! Hands on hips with a stern face usually means someone is frustrated or being very serious.", encourageFeedback:"Hands on hips + stern face = frustrated or serious. This body language says \"I mean business\" or \"I'm not happy about this.\"" },
    { difficulty:3, emoji:"\u{1F937}", text:"Your friend shrugs their shoulders when you ask what they want to do. What does the shrug mean?", choices:[{text:"They're angry at you",correct:false},{text:"They don't know or don't have a preference",correct:true},{text:"They want to go home",correct:false}], correctFeedback:"Exactly! A shrug usually means \"I don't know\" or \"I don't mind either way.\" You could suggest something!", encourageFeedback:"Shrugging is a universal body language for \"I don't know\" or \"I'm not sure.\" It's not rude \u2014 they just don't have a preference." }
);

SCENARIOS["tricky-situations"].push(
    { difficulty:1, emoji:"\u{1F4E2}", text:"A fire alarm goes off at school. What should you do?", choices:[{text:"Stay calm, follow your teacher, and walk to the meeting point",correct:true},{text:"Run as fast as you can",correct:false},{text:"Hide under your desk",correct:false}], correctFeedback:"Perfect! Staying calm and following instructions is the safest thing to do. Your teacher will guide you.", encourageFeedback:"When alarms go off, the best thing is to stay calm and follow your teacher's instructions. They know what to do!" },
    { difficulty:2, emoji:"\u{1F6B8}", text:"A stranger offers you sweets and asks you to come with them. What should you do?", choices:[{text:"Go with them because sweets are nice",correct:false},{text:"Say \"No thank you\" firmly, walk away, and tell a trusted adult immediately",correct:true},{text:"Take the sweets but don't go with them",correct:false}], correctFeedback:"That's exactly right! Never go with strangers. Say no, walk away, and tell a trusted adult right away. Your safety comes first.", encourageFeedback:"This is really important: never go with strangers, even if they offer nice things. Say \"No\", walk away, and tell a parent or teacher immediately." },
    { difficulty:3, emoji:"\u{1F4BB}", text:"You see someone being bullied in an online game chat. What could you do?", choices:[{text:"Join in so you don't become a target",correct:false},{text:"Don't respond to the bully, support the person being bullied privately, and report it",correct:true},{text:"Leave the game and forget about it",correct:false}], correctFeedback:"That's the right approach! Supporting the person privately and reporting the bully helps without making things worse.", encourageFeedback:"Online bullying is serious. The best approach: don't engage the bully, send a kind message to the person being bullied, and use the report button." }
);

SCENARIOS["feelings-check"].push(
    { difficulty:1, emoji:"\u{1F634}", text:"You're feeling really tired but you still have homework to do. What could help?", choices:[{text:"Stay up really late to finish everything",correct:false},{text:"Take a short break, have a healthy snack, then do a little bit at a time",correct:true},{text:"Don't do the homework at all",correct:false}], correctFeedback:"Smart strategy! Breaking things into small pieces with breaks helps your brain work better when you're tired.", encourageFeedback:"When you're tired, small steps work best! Take a break, have a snack, then do a little bit. You don't have to do it all at once." },
    { difficulty:2, emoji:"\u{1F92F}", text:"Everything feels like too much right now \u2014 school, friends, activities. You feel overwhelmed. What could help?", choices:[{text:"Keep pushing through and ignore the feeling",correct:false},{text:"Talk to someone you trust and figure out what you can take a break from",correct:true},{text:"Quit everything",correct:false}], correctFeedback:"That's really wise! When everything feels like too much, talking to someone helps you figure out what's most important and what can wait.", encourageFeedback:"Feeling overwhelmed is your brain saying \"this is too much.\" Talking to a trusted adult can help you figure out what to prioritise." },
    { difficulty:3, emoji:"\u{1F614}", text:"You feel left out because your friends hung out without inviting you. What's a healthy way to handle this?", choices:[{text:"Post something mean about them online",correct:false},{text:"Tell your friends calmly: \"I felt left out when you hung out without me. Can I join next time?\"",correct:true},{text:"Never talk to them again",correct:false}], correctFeedback:"That's really mature! Using \"I feel\" statements to express your feelings calmly is one of the best communication skills there is.", encourageFeedback:"Feeling left out hurts! But the healthiest response is to tell your friends calmly how you felt. \"I felt left out\" is much better than getting angry." }
);

/* ===== STAR OF THE DAY ===== */
var STAR_OF_THE_DAY = [
    { emoji:"\u{1F31E}", question:"What's a good way to greet someone in the morning?", choices:["Ignore them","Say \"Good morning!\" with a smile","Stare at them"], answer:1 },
    { emoji:"\u{1F917}", question:"What does it mean when someone offers you a hug?", choices:["They want to fight","They care about you and want to comfort you","They're cold"], answer:1 },
    { emoji:"\u{1F3B5}", question:"Your friend is singing and they're not very good. What's a kind thing to do?", choices:["Tell them they're terrible","Encourage them \u2014 \"I love that you enjoy singing!\"","Cover your ears"], answer:1 },
    { emoji:"\u{1F4DA}", question:"What should you do if you see someone drop their books?", choices:["Walk past them","Help them pick up their books","Laugh at them"], answer:1 },
    { emoji:"\u{1F37D}\uFE0F", question:"At dinner, someone is talking with food in their mouth. Is this okay?", choices:["Yes, it saves time","No \u2014 it's polite to finish chewing before talking","Only if the food is small"], answer:1 },
    { emoji:"\u{1F3C6}", question:"Your team lost a game. What's good sportsmanship?", choices:["Blame your teammates","Say \"Good game\" to the other team and try harder next time","Refuse to shake hands"], answer:1 },
    { emoji:"\u{1F4AC}", question:"Someone tells you a joke but you don't find it funny. What could you do?", choices:["Say \"That's not funny at all\"","Smile politely \u2014 you don't have to laugh but you can be kind","Walk away without saying anything"], answer:1 },
    { emoji:"\u{1F9F9}", question:"You made a mess in the kitchen. What should you do?", choices:["Leave it for someone else","Clean it up yourself","Blame the dog"], answer:0 },
    { emoji:"\u{1F44B}", question:"How do you politely get someone's attention?", choices:["Yell their name really loud","Say \"Excuse me\" and wait for them to look at you","Poke them repeatedly"], answer:1 },
    { emoji:"\u{1F381}", question:"Someone gives you a gift you don't really like. What should you say?", choices:["\"I don't like this\"","\"Thank you so much!\" \u2014 it's the thought that counts","Nothing, just put it down"], answer:1 },
    { emoji:"\u{1F6AA}", question:"You need to enter a room where people are having a meeting. What do you do?", choices:["Burst in loudly","Knock gently and wait","Stand outside forever"], answer:1 },
    { emoji:"\u{1F9D1}\u200D\u{1F91D}\u200D\u{1F9D1}", question:"What's one way to make a new friend?", choices:["Wait for them to talk to you first","Ask them about something they like","Follow them around silently"], answer:1 },
    { emoji:"\u{1F4F1}", question:"Is it polite to look at your phone while someone is talking to you?", choices:["Yes, you can multitask","No \u2014 it's respectful to give them your attention","Only if the conversation is boring"], answer:1 },
    { emoji:"\u{1F622}", question:"Your friend is crying. What's the FIRST thing you should do?", choices:["Tell them to stop crying","Ask gently \"What's wrong?\" or just sit with them","Ignore them and walk away"], answer:1 }
];

/* ===== FEELINGS VOCABULARY ===== */
var FEELINGS_VOCAB = [
    { word:"Frustrated", emoji:"\u{1F624}", meaning:"When something isn't working the way you want and you feel stuck or annoyed.", example:"I felt frustrated when I couldn't solve the maths problem." },
    { word:"Overwhelmed", emoji:"\u{1F635}", meaning:"When there's too much happening and your brain feels full.", example:"I felt overwhelmed when I had three assignments due on the same day." },
    { word:"Grateful", emoji:"\u{1F64F}", meaning:"Feeling thankful for something or someone.", example:"I felt grateful when my friend helped me carry my books." },
    { word:"Embarrassed", emoji:"\u{1F633}", meaning:"Feeling awkward or self-conscious, usually when something unexpected happens in front of others.", example:"I felt embarrassed when I tripped in the hallway." },
    { word:"Proud", emoji:"\u{1F929}", meaning:"Feeling good about something you've achieved or done well.", example:"I felt proud when I finished my painting." },
    { word:"Jealous", emoji:"\u{1F60F}", meaning:"Wanting something that someone else has.", example:"I felt jealous when my friend got a new bike." },
    { word:"Anxious", emoji:"\u{1F630}", meaning:"Feeling worried about something that might happen in the future.", example:"I felt anxious before my first swimming lesson." },
    { word:"Disappointed", emoji:"\u{1F61E}", meaning:"Feeling let down when something doesn't go the way you hoped.", example:"I felt disappointed when the trip got cancelled." },
    { word:"Curious", emoji:"\u{1F9D0}", meaning:"Wanting to learn or know more about something.", example:"I felt curious when I saw a strange bug in the garden." },
    { word:"Lonely", emoji:"\u{1F614}", meaning:"Feeling alone or like nobody is there for you.", example:"I felt lonely on my first day at the new school." },
    { word:"Confident", emoji:"\u{1F4AA}", meaning:"Believing in yourself and feeling sure you can do something.", example:"I felt confident before my presentation because I practised a lot." },
    { word:"Calm", emoji:"\u{1F60C}", meaning:"Feeling peaceful and relaxed, like everything is okay.", example:"I felt calm after doing my breathing exercises." },
    { word:"Excited", emoji:"\u{1F389}", meaning:"Feeling really happy and energetic about something that's going to happen.", example:"I felt excited the night before my birthday party." },
    { word:"Guilty", emoji:"\u{1F625}", meaning:"Feeling bad because you did something wrong or hurt someone.", example:"I felt guilty after I said something mean to my sister." },
    { word:"Hopeful", emoji:"\u{1F31F}", meaning:"Believing that something good will happen.", example:"I felt hopeful when the teacher said I was improving." },
    { word:"Confused", emoji:"\u{1F914}", meaning:"Not understanding something or not knowing what to do.", example:"I felt confused when the instructions were too complicated." }
];

/* ===== SOCIAL RULES CARDS ===== */
var SOCIAL_RULES = [
    { emoji:"\u{1F44B}", rule:"Say hello and goodbye", detail:"When you arrive somewhere or leave, it's polite to greet people and say goodbye. A simple wave or \"Hi!\" works great." },
    { emoji:"\u{1F442}", rule:"Listen when others talk", detail:"When someone is speaking, look at them and wait until they finish before you talk. This shows you care about what they're saying." },
    { emoji:"\u{1F64B}", rule:"Raise your hand to speak in class", detail:"In class, raise your hand and wait to be called on. This gives everyone a fair chance to share their ideas." },
    { emoji:"\u{1F64F}", rule:"Say please and thank you", detail:"\"Please\" when you ask for something, \"Thank you\" when you receive it. These magic words make everyone feel respected." },
    { emoji:"\u{1F6AA}", rule:"Knock before entering", detail:"If a door is closed, knock and wait before going in. This respects other people's privacy and space." },
    { emoji:"\u{1F91D}", rule:"Take turns", detail:"In games, conversations, and activities, everyone gets a turn. Waiting patiently shows fairness and respect." },
    { emoji:"\u{1F440}", rule:"Make eye contact (when comfortable)", detail:"Looking near someone's face when they talk shows you're listening. If direct eye contact feels hard, looking at their nose or forehead works too!" },
    { emoji:"\u{1F910}", rule:"Use an indoor voice inside", detail:"Inside buildings, we use a quieter voice. Save your loud voice for outside and playgrounds!" },
    { emoji:"\u{1F6B6}", rule:"Respect personal space", detail:"Stand about an arm's length away from people. Everyone has an invisible bubble around them that feels comfortable." },
    { emoji:"\u{1F614}", rule:"Say sorry when you make a mistake", detail:"If you accidentally hurt someone or do something wrong, say \"I'm sorry\" and try to make it right. Everyone makes mistakes!" },
    { emoji:"\u{1F4AC}", rule:"Don't interrupt", detail:"Wait for a pause before speaking. If you accidentally interrupt, say \"Sorry, go ahead\" and let them finish." },
    { emoji:"\u{1F60A}", rule:"Compliment others", detail:"Saying nice things like \"Great job!\" or \"I like your drawing\" makes people feel good and strengthens friendships." }
];
